Hv work stage 3
Yuri-73/starBank pull request #10
Opened 2024-12-15 14:54 UTC by Yuri-73

Проверьте командную работу, этап 3

2024-12-16 14:45 UTC, AleksandrZhukovJava requested changes

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on pom.xml
> +			<version>42.3.2</version>
версия не нужна, она есть в родительской зависимости

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/configuration/TelegramBotConfiguration.java
> +        bot.execute(new DeleteMyCommands());  //Что делает new DeleteMyCommands()?   *?*
Удаляет дефолтные команды, что бы вы могли использовать свои если я правильно помню

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/controllers/ManagementController.java
> +        return str;
интересная конструкция, лучше все таки
`return pomXmlParser.getData();`

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +    public static final String RECOMMEND = "/recommend sheron.berge";
лучше убрать в отдельный интерфейс/класс/енам

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +            if ((START).equals(messageReceived)) {  //Если текст команды соответствует "/start", то выводится соответствующее приветствие пользователю.
Если боитесь что один из параметров может быть null лучше взять за привычку использовать Objects.equals(), еще пригодится =)

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +            if (messageReceived.startsWith("/recommend") && !messageReceived.equals("/recommend")) {
упадем если text будет null
+
messageReceived.matches("/recommend\\\s(.+)?") покрасивее

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +                    System.out.println(id);
System.out.println в финальном пре не должно быть

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +                if (parts[0].equals("/recommend")) {
тем более надо регулярку в прошлом кейсе, еще и тут можно использовать + 
двойную вложенность надо убрать

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/services/PomXmlParser.java
> +        return str;
мне кажется тут есть ошибка, протестируйте в ручном режиме бот, посмотрите что он пришлет в чат

2024-12-16 14:45 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/services/PomXmlParser.java
> +        System.out.println("{\n\"name\": " + name + "\n" + "\"version\": " + version + "\n}");
Такие вещи лучше собирать через StringBuilder

2024-12-16 16:47 UTC, Yuri-73 commented on src/main/java/com/example/starBank/controllers/ManagementController.java
> +        return str;
Устранено

2024-12-16 16:49 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +    public static final String RECOMMEND = "/recommend sheron.berge";
Удалил, т.к. вторая константа вообще не применяется в этом контроллере.

2024-12-16 18:45 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +            if ((START).equals(messageReceived)) {  //Если текст команды соответствует "/start", то выводится соответствующее приветствие пользователю.
Заменил на Objects.equals("/start", messageReceived)

2024-12-16 18:46 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +            if (messageReceived.startsWith("/recommend") && !messageReceived.equals("/recommend")) {
Исправил на messageReceived.matches("/recommend\\s(.+)?")

2024-12-16 18:46 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +                    System.out.println(id);
Удалил

2024-12-16 18:47 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +                if (parts[0].equals("/recommend")) {
Вложенность if'а удалил

2024-12-16 18:49 UTC, Yuri-73 commented on pom.xml
> +			<version>42.3.2</version>
Удалил

2024-12-16 18:49 UTC, Yuri-73 commented on src/main/java/com/example/starBank/configuration/TelegramBotConfiguration.java
> +        bot.execute(new DeleteMyCommands());  //Что делает new DeleteMyCommands()?   *?*
Спасибо, понял.

2024-12-16 18:55 UTC, Yuri-73 commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +            if (messageReceived.startsWith("/recommend") && !messageReceived.equals("/recommend")) {
Мы дополнительно нашли недочёт: при задании в боте неправильного имени пользователя, система падает. Добавили для устранения ещё один запрос в  RecommendationsRepository и логику к нему в TelegramBotUpdatesListener.

2024-12-16 19:15 UTC, Yuri-73 commented on src/main/java/com/example/starBank/services/PomXmlParser.java
> +        System.out.println("{\n\"name\": " + name + "\n" + "\"version\": " + version + "\n}");
Пересобрали через StringBuilder

2024-12-16 19:19 UTC, Yuri-73 commented on src/main/java/com/example/starBank/services/PomXmlParser.java
> +        System.out.println("{\n\"name\": " + name + "\n" + "\"version\": " + version + "\n}");
Всё, наверное, устранили. Посмотри, Саша :)

2024-12-17 09:26 UTC, AleksandrZhukovJava approved these changes

2024-12-17 09:26 UTC, AleksandrZhukovJava commented on src/main/java/com/example/starBank/listener/TelegramBotUpdatesListener.java
> +                String userName = parts[1];
Не очень корректно, сообщение типа /recommend hello world у вас распарсится как 
String userName = "hello" 
По этому я и предлагал группы паттерна как в прошлом боте. Но этот баг уже в самостоятельном режиме по желанию

2024-12-21 14:30 UTC, merged